import Entry from './entry.js';
import OctokitWrapper from '@stgroves/octokit-wrapper';

/**
 * Gets the current time in seconds.
 * @returns {number}
 */
const getNowInSecs = () => Date.now() / 1000;

/**
 * Converts the GitHub Action input into a valid PEM.
 * @param {String} pem
 * @returns {String}
 */
const preparePEM = pem => {
    const PATTERN = /-----BEGIN RSA PRIVATE KEY-----([\s\S]*?)-----END RSA PRIVATE KEY-----/g;
    return pem.replace(PATTERN, (_, body) => {
        const modified = body.replace(/\s+/g, '\n');
        return pem.replace(body, modified);
    });
};

/**
 * Creates an object to store as a secret.
 * @param {String} pem
 * @param {String} clientSecret
 * @param {String} refreshToken
 * @param {Number} installationID
 * @param {Number} now
 * @param {Uint8Array} privateKey
 * @param {Uint8Array} publicKey
 * @returns {SecretObject}
 */
const buildSecretObject = (pem, clientSecret, refreshToken, installationID, now, {privateKey, publicKey}) => {
    return {
        clientSecret,
        pem,
        installationID,
        refreshToken,
        refreshTokenLastUpdated: now,
        signingPrivate: privateKey,
        signingPublicKey: publicKey,
    }
};

/**
 * Creates an object to store as a data index.
 * @returns {DataObject}
 */
const buildDataIndex = () => ({
    pages: [],
    signature: ''
});

const getDataIndex = async (context) => {
    const {processedFile} = await OctokitWrapper.getFile(
        context.getAppOctokit(),
        context.owner,
        context.repo,
        '.vault',
        {branch: 'vault'}
    );
    return JSON.parse(processedFile);
};

/**
 * Sets up a repo to become the Token Manager.
 * @param {SetupContext} context Program Context.
 * @param {String} pem PEM file contents.
 * @param {String} authCode Code generated by OAuth.
 * @returns {Promise<void>}
 */
const setup = async (context, pem, authCode) => {
    console.log('Running Setup');

    try {
        const {
            appID,
            installID,
            clientSecret,
            clientID,
            owner,
            repo,
            getOrCreateAppOctokit,
            getAccessTokenFromCode,
            updateSecrets
        } = context;
        const preparedPEM = preparePEM(pem);

        const octokit = await getOrCreateAppOctokit(appID, preparedPEM, installID);

        const [_, refreshToken] = await getAccessTokenFromCode(clientID, clientSecret, authCode);
        const secretObj = buildSecretObject(
            preparedPEM,
            clientSecret,
            refreshToken,
            installID,
            getNowInSecs(),
            context.sodium.crypto_sign_keypair()
        );

        await updateSecrets(
            octokit,
            owner,
            repo,
            [
                {
                    key: 'SECRETS',
                    value: JSON.stringify(secretObj)
                }
            ]
        );
    } catch (e) {
        console.error(e);
        process.exit(1);
    }
};

/**
 *
 * @param {SecretContext} context
 * @param {Number} repoID
 * @param {Boolean} isCritical
 * @returns {Promise<void>}
 */
const createNewEntry = async (context, repoID, isCritical) => {
    const repoEntry = new Entry(isCritical);
    const tokenManagerEntry = new Entry(isCritical);

    Entry.generateEncryptionKeys(context.sodium, repoEntry, tokenManagerEntry);

    const tmObject = tokenManagerEntry.getStorageObject();
    const repoObject = repoEntry.getStorageObject();

};

export const TokenManager = Object.freeze({
    setup,
    preparePEM,
    createNewEntry
});

/**
 * @typedef {object} DataObject
 * @property {PageEntry[]} pages
 * @property {string} signature
 * @property {number[][]} pendingConfirmation
 */

/**
 * @typedef {object} PageEntry
 * @property {string} signature
 * @property {string} lastUpdated
 */