name: Add Repo to Token Manager
on:
  workflow_dispatch:
    inputs:
      repo:
        description: Repo to be added. Must be in ORG/REPO format and contain only [A-Za-z0-9.-_]
        required: true
        type: string
      isCritical:
        description: Is the repo critical to operations?
        required: false
        type: boolean
jobs:
  addRepo:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Choose a stable version

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: stgroves/token-manager
          ref: main

      - name: Install Dependencies
        run: npm install

      - name: Run Program
        env:
          EXECUTION_PATH: 'ADD_REPO'
          TARGET: ${{ inputs.repo }}
          CRITICAL: ${{ inputs.isCritical }}
          SECRETS: ${{ secrets.SECRETS }}
        run: node run-program.js --verbose