name: Request Access Token

on:
  workflow_call:
    outputs:
      access-token:
        description: "Generated access token"
        value: ${{ jobs.auth.outputs.access-token }}

jobs:
  refresh-token:
    runs-on: ubuntu-latest
    outputs:
      access-token: ${{ steps.generate-token.outputs.ACCESS_TOKEN }}
    steps:
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Choose a stable version

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: Install Dependencies
        run: npm install

      - name: Get Token
        env:
          PROGRAM_PATH: 'REQUEST'
          CLIENT_ID: 'Iv23liaI5AFKuWHs41ny'
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        id: generate-token
        run: node run-program.js --verbose