name: Refresh PAT Token

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:

jobs:
  refresh-token:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Choose a stable version

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Define Repository List File
        run: echo "REPOS=repos.txt" >> $GITHUB_ENV

      - name: Verify Repository List File
        env:
          REPOS: ${{ env.REPOS }}
        run: |
          if [ ! -f $REPOS ]; then
            echo "Error: $REPOS not found!"
            exit 1
          fi

      - name: Install Dependencies
        run: npm install @octokit/core jsonwebtoken

      - name: Get Token
        env:
          PEM: ${{ secrets.PEM }}
          INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
        run: |
          TOKEN=$(node request-access-token.js)
          echo "RECEIVED_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Validate Token
        run: |
          if [ -z "$RECEIVED_TOKEN" ]; then
            echo "Error: Token generation failed."
            exit 1
          fi

      - name: Update Secrets Across Repos
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          while IFS= read -r REPO; do
            echo "Updating secret for $REPO..."
            gh secret set ACCESS_TOKEN -b "$RECEIVED_TOKEN" --repo "$REPO" || { 
              echo "Failed to update $REPO"; exit 1; 
            }
          done < "$REPOS"